receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch: {}
  # attributes:
  #   actions:
  #     - action: upsert
  #       key: trace_id
  #       value: "{trace_id}"

exporters:
  otlphttp:
    endpoint: "https://.collect.observeinc.com/v2/otel"
    headers:
      authorization: "Bearer "

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]